services:
    mongodb:
        class: \MongoDB\Driver\Manager
            
    mongodb.factory:
        class: \Trismegiste\Strangelove\MongoDb\RepositoryFactory
        arguments:
            $manager: '@mongodb'
            $log: '@logger'

    Trismegiste\Strangelove\Profiler\MongoDbCollector:
        arguments:
            - '@mongodb.monitoring'
        tags: 
            -
                name: data_collector
                id: strangelove
                template: '@Strangelove/profiler/data_collector.html.twig'
    
    mongodb.monitoring:
        class: \Trismegiste\Strangelove\Profiler\CollectingSubscriber